#!/usr/bin/env python3
"""Generate review/data.js for an Auto-FDE engagement.

Scans the engagement directory (layout: reference/engagement-layout.md) and
emits window.FDE_DATA per templates/review/DATA-CONTRACT.md. Sections are
omitted when their inputs don't exist yet — the review page grows tab by tab.

Usage: gen-review-data.py [engagement_root]   (default: cwd)
"""
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

TEXT_EXT = {".md", ".txt", ".json", ".js", ".py", ".sh", ".yaml", ".yml", ".html", ".css", ".csv"}
MAX_FILE_BYTES = 400_000  # guard against a stray huge file bloating data.js


def read_json(path: Path):
    if not path.is_file():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as e:
        print(f"warning: unreadable {path}: {e}", file=sys.stderr)
        return None


def skill_files(skill_dir: Path):
    files = []

    def rank(p: Path):
        # contract order: SKILL.md, then references/, then evals/, then the rest
        top = p.relative_to(skill_dir).parts[0]
        return ({"references": 0, "evals": 1}.get(top, 2), p.as_posix())

    ordered = [skill_dir / "SKILL.md"] + sorted(
        (p for p in skill_dir.rglob("*") if p.is_file() and p.name != "SKILL.md"),
        key=rank,
    )
    for p in ordered:
        if not p.is_file():
            continue
        rel = p.relative_to(skill_dir).as_posix()
        if p.suffix.lower() not in TEXT_EXT:
            files.append({"path": rel, "content": f"(binary asset: {p.stat().st_size} bytes)"})
            continue
        if p.stat().st_size > MAX_FILE_BYTES:
            files.append({"path": rel, "content": f"(file too large for review page: {p.stat().st_size} bytes)"})
            continue
        try:
            files.append({"path": rel, "content": p.read_text(encoding="utf-8")})
        except (OSError, UnicodeDecodeError) as e:
            files.append({"path": rel, "content": f"(unreadable: {e})"})
    return files


def main():
    root = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else Path.cwd()
    build = root / ".build"
    data = {"generated": datetime.now(timezone.utc).isoformat(timespec="seconds")}

    catalog = read_json(root / "catalog.json")
    if catalog:
        data["engagement"] = {
            "team": catalog.get("team", ""),
            "pluginName": catalog.get("plugin", {}).get("name", ""),
            "version": catalog.get("plugin", {}).get("version", ""),
        }
        data["catalog"] = {
            "phases": catalog.get("phases", []),
            "lanes": catalog.get("lanes", []),
            "skills": catalog.get("skills", []),
            "commands": catalog.get("commands", []),
            "agents": catalog.get("agents", []),
            "integrations": catalog.get("integrations", []),
        }

    oq = read_json(build / "open-questions.json")
    if oq:
        data["openQuestions"] = oq

    # Built skills: plugin dir named by the catalog
    if catalog:
        plugin_dir = root / catalog.get("plugin", {}).get("name", "")
        skills_dir = plugin_dir / "skills"
        if skills_dir.is_dir():
            scores = read_json(build / "verify-scores.json") or {}
            built = {}
            for d in sorted(skills_dir.iterdir()):
                if not (d / "SKILL.md").is_file():
                    continue
                entry = {"files": skill_files(d)}
                s = scores.get(d.name)
                if s:
                    entry["scores"] = {
                        "fidelity": s.get("scores", {}).get("fidelity"),
                        "bestPractices": s.get("scores", {}).get("bestPractices"),
                        "triggering": s.get("scores", {}).get("triggering"),
                        "verdict": s.get("verdict"),
                    }
                    entry["openQuestions"] = s.get("openQuestions", [])
                built[d.name] = entry
            if built:
                data["builtSkills"] = built

    trigger = read_json(build / "trigger-report.json")
    report_md = build / "eval-report.md"
    if trigger or report_md.is_file():
        evals = {}
        if trigger:
            evals["trigger"] = trigger
        output = read_json(build / "output-evals.json")
        if output:
            evals["output"] = output
        if report_md.is_file():
            evals["reportMarkdown"] = report_md.read_text(encoding="utf-8")
        data["evals"] = evals

    deploy = read_json(build / "deploy.json")
    if deploy:
        data["deploy"] = deploy

    out_dir = root / "review"
    out_dir.mkdir(exist_ok=True)
    out = out_dir / "data.js"
    out.write_text(
        "// Generated by auto-fde scripts/gen-review-data.py — do not hand-edit.\n"
        "window.FDE_DATA = " + json.dumps(data, indent=2, ensure_ascii=False) + ";\n",
        encoding="utf-8",
    )
    tabs = [t for t in ("catalog", "builtSkills", "evals", "deploy") if t in data]
    print(f"wrote {out} ({out.stat().st_size:,} bytes) — tabs: {', '.join(tabs) or 'none (empty state)'}")


if __name__ == "__main__":
    main()
